CREATE TABLE public_keys (
  key_id VARCHAR(255) NOT NULL PRIMARY KEY,
  nickname VARCHAR(255) NOT NULL,
  metadata TEXT,
  is_me TINYINT NOT NULL DEFAULT 0,
  public_key TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
